POST http://localhost:3333/v1/users
Content-Type: application/json

{
    "name": "Jon Show",
    "email": "jon.show@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3333/v1/users
Content-Type: application/json

###
PUT http://localhost:3333/v1/users/1
Content-Type: application/json

{
    "password": "567890"
}

###
DELETE http://localhost:3333/v1/users/1
Content-Type: application/json