POST http://localhost:3333/v1/users
Content-Type: application/json

{
    "name": "Aria Stark",
    "email": "aria.stark@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3333/v1/users
Content-Type: application/json

###
GET http://localhost:3333/v1/users/1
Content-Type: application/json

###
PUT http://localhost:3333/v1/users/1
Content-Type: application/json

{
    "current_password": "123456",
    "new_password": "567890"
}

###
DELETE http://localhost:3333/v1/users/1
Content-Type: application/json